name: test
author: Alexander Zakharchuk
email: alexz@aswsyst.cz
version: '1.0'
url: a.a
title: 'test'
icon: database
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }